"""add_clerk_user_id

Revision ID: fb6d4ef46e79
Revises: 0003_resume_s3_fields
Create Date: 2026-05-10 10:33:48.388555

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'fb6d4ef46e79'
down_revision: str | None = '0003_resume_s3_fields'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resumes', 'file_type',
               existing_type=sa.VARCHAR(length=50),
               comment='pdf | docx',
               existing_comment='pdf | docx | txt',
               existing_nullable=True)
    op.alter_column('templates', 'id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Slug PK, e.g. 'minimal'",
               existing_nullable=False)
    op.add_column('users', sa.Column('clerk_user_id', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('plan_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_stripe_customer_id'), 'users', type_='unique')
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_users_stripe_subscription_id'), 'users', ['stripe_subscription_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_stripe_subscription_id'), table_name='users')
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.create_unique_constraint(op.f('uq_users_stripe_customer_id'), 'users', ['stripe_customer_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('users', 'plan_expires_at')
    op.drop_column('users', 'stripe_subscription_id')
    op.drop_column('users', 'clerk_user_id')
    op.alter_column('templates', 'id',
               existing_type=sa.VARCHAR(length=100),
               comment="Slug PK, e.g. 'minimal'",
               existing_nullable=False)
    op.alter_column('resumes', 'file_type',
               existing_type=sa.VARCHAR(length=50),
               comment='pdf | docx | txt',
               existing_comment='pdf | docx',
               existing_nullable=True)
    # ### end Alembic commands ###
